version: "3"
services:
  dev-db:
    image: docker.io/library/mysql:8
    environment:
      TZ: "/usr/share/zoneinfo/UTC"
      MYSQL_ROOT_HOST: "%"
      MYSQL_HOST: localhost
      MYSQL_DATABASE: probematic
      MYSQL_ROOT_PASSWORD: "probematic"
      MYSQL_CONNECTION_LIMIT: 30
      MYSQL_TCP_PORT: 3306
    ports:
      - "3311:3306"
    volumes:
      - data-probematic-dev-db:/var/lib/mysql
volumes:
  data-probematic-dev-db:
