---
version: "3.8"
services:
  redis:
    image: docker.io/library/redis:7
    restart: always
    command:
      [
        bash,
        -c,
        "docker-entrypoint.sh --appendonly yes --save 60 1 --notify-keyspace-events AKE --requirepass devpassword123",
      ]
    user: "1000:1000"
    ports:
      - "6379:6379"
    volumes:
      - "./redis-dev:/data:z"
    labels:
      io.containers.autoupdate: registry
  smtp4dev:
    image: docker.io/rnwood/smtp4dev:v3
    ports:
      # web port
      - "127.0.0.1:5002:80"
      # smtp port
      - "127.0.0.1:2500:25"
      # imap port
      - "127.0.0.1:1430:143"
    volumes:
      - ./data-smtp4dev:/smtp4dev
    restart: unless-stopped
